# fly.toml app configuration file generated for api-floral-waterfall-9034 on 2024-11-29T09:22:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-floral-waterfall-9034'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
